// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo4tIuHLyf2BFpqtGVKM9Eq6O2XL0ouWk',
    appId: '1:557335427034:web:9b54d9dff454d4e97af2e3',
    messagingSenderId: '557335427034',
    projectId: 'application-92923',
    authDomain: 'application-92923.firebaseapp.com',
    storageBucket: 'application-92923.appspot.com',
    measurementId: 'G-T82J66J2V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV1U6RObPReORAoC82WIeL21GDU697XA4',
    appId: '1:557335427034:android:f2f01781155bfa577af2e3',
    messagingSenderId: '557335427034',
    projectId: 'application-92923',
    storageBucket: 'application-92923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCofePxFTu7AvtTiJYJ3w-pgM2iBv0PtCM',
    appId: '1:557335427034:ios:e7e681f23d2c07467af2e3',
    messagingSenderId: '557335427034',
    projectId: 'application-92923',
    storageBucket: 'application-92923.appspot.com',
    iosBundleId: 'com.example.meterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCofePxFTu7AvtTiJYJ3w-pgM2iBv0PtCM',
    appId: '1:557335427034:ios:e7e681f23d2c07467af2e3',
    messagingSenderId: '557335427034',
    projectId: 'application-92923',
    storageBucket: 'application-92923.appspot.com',
    iosBundleId: 'com.example.meterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo4tIuHLyf2BFpqtGVKM9Eq6O2XL0ouWk',
    appId: '1:557335427034:web:d4aa73b934cc91017af2e3',
    messagingSenderId: '557335427034',
    projectId: 'application-92923',
    authDomain: 'application-92923.firebaseapp.com',
    storageBucket: 'application-92923.appspot.com',
    measurementId: 'G-ZLESTTL9W0',
  );
}
