import 'package:meter_app/utils/pref_util.dart';

class LanguageUtils {
  static bool isEnglishLang() {
    bool? isEnglish = PrefUtil.getBool(PrefUtil.language);
    print("Is English $isEnglish");
    return isEnglish ?? false;
  }

  static Map<String, String> getEnglishTranslations() {
    return {
      "Get Started Now": "Get Started Now",
      "Create an account or log in to explore about our app":
          "Create an account or log in to explore about our app",
      "Log In": "Log In",
      "Sign Up": "Signup",
      "Phone Number": "Phone Number",
      "Remember me": "Remember me",
      "Send Code": "Send Code",
      "Seller": "Seller",
      "Customer": "Customer",
      "Provider": "Provider",
      "Company": "Company",
      "Establishment": "Establishment",
      "Facility name": "Facility name",
      "Nasr Company": "Nasr Company",
      "Facility Number": "Facility Number",
      "Commercial Registration": "Commercial Registration",
      "Facility Activity": "Facility Activity",
      "Activity will be here": "Activity will be here",
      "Register": "Register",
      "General Info": "General Info",
      "Muhammad": "Muhammad",
      "Owner Name": "Owner Name",
      "Enter manager name": "Enter manager name",
      "Manager Name": "Manager Name",
      "Manager Phone Number": "Manager Phone Number",
      "Description": "Description",
      "Continue": "Continue",
      "Region": "Region",
      "Enter Region": "Enter Region",
      "Faisalabad": "Faisalabad",
      "Multan": "Multan",
      "Select City": "Select City",
      "City": "City",
      "Lahore": "Lahore",
      "Rawalpindi": "Rawalpindi",
      "Select Neighborhood": "Select Neighborhood",
      "Neighborhood": "Neighborhood",
      "Location": "Location",
      "Enter your password": "Enter your password",
      "Re-enter password": "Re-enter password",
      "Confirm Password": "Confirm Password",
      "I agree to the ": "I agree to the ",
      "terms & conditions": "terms & conditions",
      " by creating account.": " by creating account.",
      "Commitment to the accuracy of inforamtion.":
          "Commitment to the accuracy of inforamtion.",
      "Commitment to pay meter app dues, estimated at 10% of the project value.":
          "Commitment to pay meter app dues, estimated at 10% of the project value.",
      "Face Id Security": "Face Id Security",
      "Secure your account with your face":
          "Secure your account with your face",
      "using Face ID": "using Face ID",
      "Please position your face in front of":
          "Please position your face in front of",
      "the camera to authenticate with Face ID":
          "the camera to authenticate with Face ID",
      "Authentication successful": "Authentication successful",
      "Skip": "Skip",
      "Secure your account with your fingerprint":
          "Secure your account with your fingerprint",
      "using Touch ID": "using Touch ID",
      "Please place your finger": "Please place your finger",
      "on the fingerprint sensor to get started":
          "on the fingerprint sensor to get started",
      "Created Account": "Created Account",
      "Congratulations! Your account has been created. Click continue to start":
          "Congratulations! Your account has been created. Click continue to start",
      "Done": "Done",
      "Home": "Home",
      "Store": "Store",
      "Requests": "Requests",
      "Chat": "Chat",
      "Account": "Account",
      "Makka,Saudi Arabia": "Makka,Saudi Arabia",
      "Good Morning,": "Good Morning,",
      "Choose your service and start": "Choose your service and start",
      "Publish a device": "Publish a device",
      "Type of device": "Type of device",
      "Buy": "Buy",
      "Sell": "Sell",
      "Rent": "Rent",
      "Enter device name": "Enter device name",
      "Device Name": "Device Name",
      "Choose device category": "Choose device category",
      "Device Category": "Device Category",
      "Device1": "Device1",
      "Device2": "Device2",
      "Enter Model": "Enter Model",
      "Model": "Model",
      "Enter Manufacturing Year": "Enter Manufacturing Year",
      "Manufacturing Year": "Manufacturing Year",
      "Enter device price": "Enter device price",
      "Write details": "Write details",
      "Details": "Details",
      "Click to Upload Device Photos": "Click to Upload Device Photos",
      "(Maximum file size: 25MB)": "(Maximum file size: 25MB)",
      "privacy policy & terms": "privacy policy & terms",
      "ofServices": " of services.",
      "Commitment to the accuracy of inforamtion. ":
          "Commitment to the accuracy of inforamtion. ",
      "Post Device": "Post Device",
      "Your device has been posted. Click to show providers proposals":
          "Your device has been posted. Click to show providers proposals",
      "Successfully🎉": "Successfully🎉",
      "Profile": "Profile",
      "Payment Methods": "Payment Methods",
      "Help Center": "Help Center",
      "Language": "Language",
      "Terms Of Services": "Terms Of Services",
      "Privacy Policy": "Privacy Policy",
      "Search": "Search",
      "About App": "About App",
      "Logout": "Logout",
      "Are you sure to logout?": "Are you sure to logout?",
      "Name": "Name",
      "Enter Your Name": "Enter Your Name",
      "Email": "Email",
      "Enter Address": "Enter Address",
      "Address": "Address",
      "Faisalbad": "Faisalbad",
      "Office": "Office",
      "Engineering Office": "Engineering Office",
      "Type Of Activity": "Type Of Activity",
      "Office1": "Office1",
      "Office2": "Office2",
      "License Number": "License Number",
      "Here would be description": "Here would be description",
      "Description Of Services": "Description Of Services",
      "Description Of Service": "Description Of Service",
      "The Owner Name": "The Owner Name",
      "Date of commercial registration": "Date of commercial registration",
      "Enter Neighborhood": "Enter Neighborhood",
      "Message": "Message",
      "Message would be here okk": "Message would be here okk",
      "Report": "Report",
      "Block": "Block",
      "Delete Chat": "Delete Chat",
      "Record": "Record",
      "Gallery": "Gallery",
      "Create an offer": "Create an offer",
      "Code has been send": "Code has been send to",
      "Haven’t got the code yet?": "Haven’t got the code yet? ",
      "Resend": "Resend",
      "Verify Code": "Verify Code",
      "You have been logged in": "You have been logged in",
      "Congratulations! Your phone number has been verified. Click continue to start":
          "Congratulations! Your phone number has been verified. Click continue to start",
      "Start": "Start",
      "Help": "Help",
      "How do I create a new account?": "How do I create a new account?",
      "General": "General",
      "Payment": "Payment",
      "Go To AutoCard": "Go To AutoCard",
////New Start
      "Change User Information": "Change User Information",
      "Select": "Select",
      "Cancel": "Cancel",
      "Save": "Save",
      "Enter facility name": "Enter facility name",
      "Enter facility number": "Enter facility number",
      "Enter Commercial Registration": "Enter Commercial Registration",
      "Service Provider": "Service Provider",
      "Enter owner name": "Enter owner name",
      "Type a message...": "Type a message...",
      "Password": "Password",
      "Survey Offices": "Survey Offices",
      "Categories": "Categories",
      "Services": "Services",
      "See All": "See All",
      "Explore Products": "Explore Products",
      "Electrical Machine": "Electrical Machine",
      "Device Specification": "Device Specification",
      "Enter License Number": "Enter License Number",
      "(Optional)": "(Optional)",
      "Enter City": "Enter City",
      "Touch ID Security": "Touch ID Security",
      "Secure your account with your fingerprint using Touch ID":
          "Secure your account with your fingerprint using Touch ID",
      "Please place your finger on the fingerprint sensor to get started":
          "Please place your finger on the fingerprint sensor to get started",
      "Enter your email": "Enter your email",
      "Completed": "Completed",
      "Active": "Active",
      "New": "New",
      "Survey Report": "Survey Report",
      "+10 Proposals": "+10 Proposals",
      "View All Proposal": "View All Proposal",
      "Requests Near You": "Requests Near You",
      "Construction Estimation": "Construction Estimation",
      "Apply Now": "Apply Now",
      "Click to upload": "Click to upload",
      "Tax": "Tax",
      "Enter Tax": "Enter Tax",
      "Price": "Price",
      "Enter Price": "Enter Price",
      "Fees": "Fees",
      "Request Pricing": "Request Pricing",
      "Consolation": "Consolation",
      "Total": "Total",
      "Write Details": "Write Details",
      "Apply": "Apply",
      "Applied Proposal": "Applied Proposal",
      "Your proposal has been applied. wait approvment from customer,":
          "Your proposal has been applied. wait approvment from customer,",
      "There are a lot of requests waiting for you":
          "There are a lot of requests waiting for you",
      "Proposals": "Proposals",
      "Request a service": "Request a service",
      "Type of activity": "Type of activity",
      "Request Service": "Request Service",
      "Engineering Job": "Engineering Job",
      "Purpose Of Pricing": "Purpose Of Pricing",
      "Choose purpose of pricing": "Choose purpose of pricing",
      "Choose purpose of cadastral report":
          "Choose purpose of cadastral report",
      "Purpose Of Survey Report": "Purpose Of Survey Report",
      "Survey Report1": "Survey Report1",
      "Survey Report2": "Survey Report2",
      "Instrument Number": "Instrument Number",
      "Enter Instrument Number": "Enter Instrument Number",
      "Survey Report Number": "Survey Report Number",
      "Enter Report Number": "Enter Report Number",
      "Type Of Certificate": "Type Of Certificate",
      "Residential": "Residential",
      "Commercial": "Commercial",
      "Investment": "Investment",
      "Governmental": "Governmental",
      "Industrial": "Industrial",
      "Other": "Other",
      "Enter neighborhood": "Enter neighborhood",
      "Piece Number": "Piece Number",
      "Enter Piece Number": "Enter Piece Number",
      "Chart Number": "Chart Number",
      "Enter chart number": "Enter chart number",
      "Applicant Type": "Applicant Type",
      "Owner": "Owner",
      "Dealer": "Dealer",
      "Applicant's name": "Applicant's name",
      "Enter Applicant's name": "Enter Applicant's name",
      "ID Number": "ID Number",
      "Enter id number": "Enter id number",
      "Submit Request": "Submit Request",
      "What is your purpose for pricing?": "What is your purpose for pricing?",
      "Survey report": "Survey report",
      "Building conformity certificate": "Building conformity certificate",
      "Construction completion certificate":
          "Construction completion certificate",
      "Construction license": "Construction license",
      "Correcting the condition of an existing building":
          "Correcting the condition of an existing building",
      "Building compliance certificate": "Building compliance certificate",
      "Occupancy certificate": "Occupancy certificate",
      "Choose": "Choose",
      "What is your purpose for issuing a survey report?":
          "What is your purpose for issuing a survey report?",
      "Issuing a building permit": "Issuing a building permit",
      "Expropriation": "Expropriation",
      "Emptying": "Emptying",
      "Digging well": "Digging well",
      "Request to sort real estate units": "Request to sort real estate units",
      "Sorting built-up lands (duplexes)": "Sorting built-up lands (duplexes)",
      "Post Request": "Post Request",
      "Your request has been posted. Click to show providers proposals":
          "Your request has been posted. Click to show providers proposals",
      "Consolation Title": "Consolation Title",
      "Enter consolation title": "Enter Consolation Title",
      "Consolation Type": "Consolation Type",
      "Engineering": "Engineering",
      "Real estate": "Real estate",
      "Commitment to pay Meter application dues":
          "Commitment to pay Meter application dues",
      "Agency Number": "Agency Number",
      "University Degree": "University Degree",
      "Diploma": "Diploma",
      "Specialization": "Specialization",
      "Do you have experience": "Do you have experience",
      "Yes": "Yes",
      "No": "No",
      "Choose Your Specialization": "Choose Your Specialization",
      "If yes, write experience here": "If yes, write experience here",
      "Enter name": "Enter name",
      "Enter email": "Enter email",
      "Preferred city work in": "Preferred city work in",
      "Enter city Name": "Enter city Name",
      "Surveying engineer": "Surveying engineer",
      "Structural engineer": "Structural engineer",
      "Safety engineer": "Safety engineer",
      "What is your Specialization?": "What is your Specialization?",
      "Your job has been posted. Click to show providers proposals":
          "Your job has been posted. Click to show providers proposals",
      "Post Job": "Post Job",
      "Survey Reports": "Survey Reports",
      "Building Completion Certificate": "Building Completion Certificate",
      "Design Work": "Design Work",
      "Occupancy Certificate": "Occupancy Certificate",
      "10+ Proposals": "10+ Proposals",
      "- Minimum angle reading 0.1 second - 4000m prism range with accuracy 1.5 mm + 2ppm - 500m NP range with accuracy 2 mm+ 2ppm - Fast and ultra-powerful advance EDM - Advanced Angle Accuracy , IACS - Measuring time: Fine 0.9 sec, Rapid 0.6 sec, tracking 0.4 sec - Touch screen, Large Graphics display":
          "- Minimum angle reading 0.1 second - 4000m prism range with accuracy 1.5 mm + 2ppm - 500m NP range with accuracy 2 mm+ 2ppm - Fast and ultra-powerful advance EDM - Advanced Angle Accuracy , IACS - Measuring time: Fine 0.9 sec, Rapid 0.6 sec, tracking 0.4 sec - Touch screen, Large Graphics display",

      "Type your review": "Type your review",
      "Submit": "Submit",
      "Service Rating": "Service Rating",
      ////////////////////////////New Start///////////////////
      "Accept": "Accept",
      "Decline": "Decline",
      "Electrical Machete": "Electrical Machete",
      "Topcon Auto level AT-B2": "Topcon Auto level AT-B2",
      "SAR": "SAR",
      ///////////////Short Text/////////////////////
      "is required": "is required",
      "Email is required": "Email is required",
      "Email must be valid": "Email must be valid",
      "Length must be greater than": "Length must be greater than",
      "Length must be less than": "Length must be less than",
      ///////////////////Please Fill All Fields
      "Please fill all fields": "Please fill all fields",
      "Please enter valid phone number": "Please enter valid phone number",
      "Please enter valid manager phone number":
          "Please enter valid manager phone number",
      "Please pick an image": "Please pick an image",
      "Please pick image first": "Please pick image first",
      "Both password must be equal": "Both password must be equal",
      "You should agree all agreements": "You should agree all agreements",
      "Delivering Service": "Delivering Service",
/////////////////////////////////////New Start/////////////////////
      "Welcome To ": "Welcome To ",
      "Your Trusted Partner in Engineering and Surveying Solutions":
          "Your Trusted Partner in Engineering and Surveying Solutions",
      "Log In With Phone Number": "Log In With Phone Number",
      "Face ID Security": "Face ID Security",
      "Log In your account with your face using face id":
          "Log In your account with your face using face id",
      "Please position your face in front of the camera to authenticate with face id":
          "Please position your face in front of the camera to authenticate with face id",
      "Write Description": "Write Description",
      "Click to upload \n your papers": "Click to upload \n your papers",
      "Capture": "Capture",
      "Consolation title": "Consolation title",
      "Consolation type": "Consolation type",
      "Write consolation details": "Write consolation details",
      "Click to upload\nWork copy here": "Click to upload\nWork copy here",
      "Electronic signature": "Electronic signature",
      "Enter office name": "Enter office name",
      "Print": "Print",
      "Send Work": "Send Work",
      "work has been sent": "work has been sent",
      "Congratulations! Your work has been sent":
          "Congratulations! Your work has been sent",
      "Consolation Delivery": "Consolation Delivery",
      "ID number": "ID number",
      "Enter Id number": "Enter Id number",
      "Instrumental Number": "Instrumental Number",
      "Enter Instrumental Number": "Enter Instrumental Number",
      "Chart number": "Chart number",
      "Enter Chart number": "Enter Chart number",
      "Street Name": "Street Name",
      "Enter street name": "Enter street name",
      "Enter the property properties": "Enter the property properties",
      "Click to Upload\n Work from Autocad":
          "Click to Upload\n Work from Autocad",
      "Electronic Signature": "Electronic Signature",
      "North Direction": "North Direction",
      "Enter height": "Enter height",
      "Height": "Height",
      "Enter boundaries": "Enter boundaries",
      "Boundaries by nature": "Boundaries by nature",
      "Boundaries by deed": "Boundaries by deed",
      "Boundaries by plan": "Boundaries by plan",
      "Next Direction": "Next Direction",
      "East Direction": "East Direction",
      "South Direction": "South Direction",
      "West Direction": "West Direction",
      "Title": "Title",
      "Enter title": "Enter title",
      "Choose Service Type": "Choose Service Type",
      "Service Type": "Service Type",
      "Agency number": "Agency number",
      "Agree to the ": "Agree to the ",
      ///////////////////////////////////////////New//////////
      "Enter Description": "Enter Description",
      "Meter Store": "Meter Store",

      "Error": "Error",
      "Request Info": "Request Info",
      "Consolation delivery": "Consolation delivery",

      /////////////////////////////////////New Text///////////////////////
      "Lorem ipsum dolor sit amet consectetur. Dignissim tortor dictum justo lorem suspendisse turpis integer eu. Elementum commodo ultrices sodales sed leo. Sed elit quis nisi laoreet mauris bibendum..":
          "Lorem ipsum dolor sit amet consectetur. Dignissim tortor dictum justo lorem suspendisse turpis integer eu. Elementum commodo ultrices sodales sed leo. Sed elit quis nisi laoreet mauris bibendum..",
      "Lorem ipsum dolor sit amet consectetur. Dictumst aenean sit viverra sapien purus phasellus. Pulvinar viverra tincidunt aenean velit ut nisl diam. Eu sed commodo pellentesque augue tincidunt. Urna euis....":
          "Lorem ipsum dolor sit amet consectetur. Dictumst aenean sit viverra sapien purus phasellus. Pulvinar viverra tincidunt aenean velit ut nisl diam. Eu sed commodo pellentesque augue tincidunt. Urna euis....",
      "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles. Ma quande lingues coalesce, li grammatica del resultant lingue es plu simplic e regulari quam ti del coalescent lingues. Li nov lingua franca va esser plu simplic e regulari quam li existent Europan lingues.\n\nIt va esser tam simplic quam Occidental in fact, it va esser Occidental. A un Angleso it va semblar un simplificat Angles, quam un skeptic Cambridge amico dit me que Occidental es.Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.":
          "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles. Ma quande lingues coalesce, li grammatica del resultant lingue es plu simplic e regulari quam ti del coalescent lingues. Li nov lingua franca va esser plu simplic e regulari quam li existent Europan lingues.\n\nIt va esser tam simplic quam Occidental in fact, it va esser Occidental. A un Angleso it va semblar un simplificat Angles, quam un skeptic Cambridge amico dit me que Occidental es.Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.",
      """
  To create a new account, please follow these simple steps: 

Open the app and navigate to the login screen. 
Below the login form, you'll see an option to "Register" Tap on that. 
You will be prompted to enter your Phone Number, Email and Full Name for your account. Please make sure to use a valid Phone Number. 
After entering your Phone Number, Email and Full Name, tap on the "Register" button.
A code will be sent to your phone number provided for verification. Please check your inbox and enter the code in the Verification screen to verify your account. 
Once your account is verified, the app will automatically log you in. 
You can enter some other personal information or skip it. 
You can set the required security level for your account or ignore it. 
You are now done creating your account. 

If you encounter any issues during the sign-up process, feel free to reach out to our support team for assistance.
  """: """
  To create a new account, please follow these simple steps: 

Open the app and navigate to the login screen. 
Below the login form, you'll see an option to "Register" Tap on that. 
You will be prompted to enter your Phone Number, Email and Full Name for your account. Please make sure to use a valid Phone Number. 
After entering your Phone Number, Email and Full Name, tap on the "Register" button.
A code will be sent to your phone number provided for verification. Please check your inbox and enter the code in the Verification screen to verify your account. 
Once your account is verified, the app will automatically log you in. 
You can enter some other personal information or skip it. 
You can set the required security level for your account or ignore it. 
You are now done creating your account. 

If you encounter any issues during the sign-up process, feel free to reach out to our support team for assistance.
  """
      ////////New large Start
    };
  }

  static Map<String, String> getArabicTranslations() {
    return {
      "Get Started Now": "أبدا الأن",
      "Create an account or log in to explore about our app":
          "إنشاء حساب أو تسجيل الدخول لاستكشاف تطبيقنا",
      "Log In": "تسجيل الدخول",
      "Sign Up": "الاشتراك",
      "Phone Number": "الهاتف الرقم",
      "Remember me": "تذكرني",
      "Send Code": "إرسال الرمز",
      "Seller": "البائع",
      "Customer": "العميل",
      "Provider": "مزود",
      "Seller Provider": "مزود خدمة", //Skipped//
      "Company": "الشركة",
      "Establishment": "المنشأة",
      "Facility name": "اسم المنشأة",
      "Nasr Company": "شركة نصر", //Skipped
      "Facility Number": "رقم المنشأة",
      "Commercial Registration": "التسجيل التجاري",
      "Facility Activity": "نشاط المنشأة",
      "Activity will be here": "النشاط سيكون هنا", //Skipped
      "Register": "تسجيل",
      "General Info": "معلومات عامة",
      "Muhammad": "محمد",
      "Owner Name": "اسم المالك",
      "Enter manager name": "أدخل اسم المدير",
      "Manager Name": "اسم المدير",
      "Manager Phone Number": "رقم هاتف المدير",
      "Description": "وصف",
      "Continue": "متابعة",
      "Region": "المنطقة",
      "Enter Region": "أدخل المنطقة",
      "Faisalabad": "فيصل آباد",
      "Multan": "ملتان",
      "Select City": "اختر مدينة",
      "City": "المدينة",
      "Request Info": "طلب معلومات", //Skipped
      "Consolation delivery": "تسليم العزاء", //Skipped //Consultation
      "Lahore": "لاهور",
      "Rawalpindi": "روالبندي",
      "Select Neighborhood": "اختر الحي",
      "Neighborhood": "الحي",
      "Location": "الموقع",
      "Enter your password": "أدخل كلمة المرور الجديدة",
      "Re-enter password": "إعادة إدخال كلمة المرور",
      "Confirm Password": "تأكيد كلمة المرور",
      "I agree to the ": "أنا أوافق على",
      "terms & conditions": "الشروط والأحكام",
      " by creating account.": "بإنشاء حساب.",
      "Commitment to the accuracy of information.": "الالتزام بدقة المعلومات.",
      "Commitment to pay meter app dues, estimated at 10% of the project value.":
          "الالتزام بسداد مستحقات تطبيق العدادات والمقدرة بـ 10% من قيمة المشروع.",
      "Face Id Security": "أمان معرف الوجه",
      "Secure your account with your face": "تأمين حسابك بوجهك",
      "using Face ID": "باستخدام Face ID",
      "Please position your face in front of": "يرجى وضع وجهك أمامه",
      "the camera to authenticate with Face ID":
          "الكاميرا للمصادقة باستخدام Face ID",
      "Authentication successful": "نجحت المصادقة",
      "Skip": "تخطي",
      "touchId": "أمان بصمة الإصبع", //Skipped
      "Secure your account with your fingerprint": "تأمين حسابك ببصمة إصبعك",
      "using Touch ID": "باستخدام Touch ID",
      "Please place your finger": "يرجى وضع إصبعك",
      "on the fingerprint sensor to get started":
          "على مستشعر بصمة الإصبع للبدء",
      "Created Account": "تم إنشاء الحساب",
      "Congratulations! Your account has been created. Click continue to start":
          "تهانينا! لقد تم انشاء الحساب بنجاح انقر فوق تم للبدء",
      "Done": "تم",
      "Home": "الصفحة الرئيسية",
      "Store": "المتجر",
      "Requests": "الطلبات",
      "Chat": "دردشة",
      "Account": "الحساب",
      "Makka,Saudi Arabia": "مكة المكرمة، العربية السعودية",
      "Good Morning,": "صباح الخير يا منجي!",
      "Choose your service and start": "اختر خدمتك وابدأ الان",
      "Publish a device": "نشر جهاز",
      "Type of device": "نوع الجهاز",
      "Buy": "شراء",
      "Sell": "بيع",
      "Rent": "تأجير",
      "Enter device name": "ادخل اسم الجهاز",
      "Device Name": "اسم الجهاز",
      "Choose device category": "اختر فئة الجهاز",
      "Device Category": "فئة الجهاز",
      "Device1": "جهاز1",
      "Device2": "جهاز2",
      "Enter Model": "ادخل الموديل",
      "Model": "الموديل",
      "Enter Manufacturing Year": "أدخل سنة التصنيع",
      "Manufacturing Year": " سنة التصنيع",
      "Enter device price": "أدخل سعر الجهاز",
      "Write details": "اكتب التفاصيل",
      "Details": "تفاصيل",
      "Click to Upload Device Photos": "انقر للتحميل",
      "(Maximum file size: 25MB)": "(الحد الأقصى لحجم الملف: 25 ميجابايت)",
      "privacy policy & terms": "سياسة الخصوصية وشروط",
      "ofServices": "الخدمة.",
      "Commitment to the accuracy of inforamtion. ": "الالتزام بدقة المعلومات.",

      "Post Device": "نشر الجهاز",
      "Your device has been posted. Click to show providers proposals":
          "لقد تم نشر جهازك. ,انقر لإظهار مقترحات مقدمي الخدمة",
      "Successfully🎉": "بنجاح🎉",
      "Profile": "الملف الشخصي",
      "Payment Methods": "طرق الدفع",
      "Help Center": "مركز المساعدة",
      "Language": "اللغة",
      "Terms Of Services": "شروط الخدمة",
      "Privacy Policy": "سياسة الخصوصية",
      "Search": "بحث",
      "About App": "حول التطبيق",
      "Logout": "تسجيل الخروج",
      "Are you sure to logout?": "هل انت متاكد من تسجيل الخروج؟",
      "Name": "الأسم",
      "Enter Your Name": "أدخل اسمك",
      "Email": "البريد الإلكتروني",

      "Enter Address": "أدخل العنوان",
      "Address": "عنوان",
      "Faisalbad": "فيصل آباد",
      "Office": "مكتب",
      "Engineering Office": "مكتب المهندسين",
      "Type Of Activity": "نوع النشاط",
      "Office1": "مكتب1",
      "Office2": "مكتب2",
      "License Number": "رقم الترخيص",
      "Here would be description": "هنا سيكون الوصف",
      "Description Of Services": "وصف الخدمات",
      "Description Of Service": "وصف الخدمة",
      "The Owner Name": "اسم المالك",
      "Date of commercial registration": "تاريخ التسجيل التجاري",
      "Enter Neighborhood": "أدخل الحي",
      "Message": "رسالة",
      "Message would be here okk": "الرسالة ستكون هنا حسناً",
      "Report": "تقرير",
      "Block": "حاجز",
      "Delete Chat": "حذف الدردشة",
      "Record": "تسجيل",
      "Gallery": "صالة عرض",
      "Create an offer": "قم بإنشاء عرض",
      "Code has been send": "تم إرسال الرمز إلى",
      "Haven’t got the code yet?": "لم تحصل على الرمز بعد؟",
      "Resend": "أعد إرسال الرمز",
      "Verify Code": "التحقق من الرمز",
      "You have been logged in": "لقد تم تسجيل الدخول",
      "Congratulations! Your phone number has been verified. Click continue to start":
          "تهانينا! ,رقم هاتفك لديه,تم التحقق منها. ,انقر فوق متابعة للبدء",
      "Start": "ابدأ",
      "Help": "مساعدة",
      "How do I create a new account?": "كيف أقوم بإنشاء حساب جديد؟",
      "General": "عام",
      "Payment": "الدفع",
      "Go To AutoCard": "انتقل إلى أوتوكاد",
      "Change User Information": "تعديل بيانات الحساب",
      "Select": "اختر",
      "Cancel": "إلغاء",
      "Save": "حفظ",

      ///////////////////////Start From here////////////////////////////////
      "Enter facility name": "أدخل اسم المنشأة",
      "Enter facility number": "أدخل رقم المنشأة",
      "Enter Commercial Registration": "أدخل السجل التجاري",
      "Service Provider": "مزود الخدمة",
      "Enter owner name": "أدخل اسم المالك",
      "Type a message...": "اكتب رسالة...",
      "Password": "كلمة المرور",
      "Survey Offices": "المسح المكاتب",
      "Categories": "الفئات",
      "Services": "الخدمات",
      "See All": "مشاهدة الكل",
      "Explore Products": "استكشاف المنتجات",
      "Electrical Machine": "منجل كهربائي",
      "Device Specification": "مواصفات الجهاز",
      "Enter License Number": "أدخل رقم الترخيص",
      "(Optional)": "(إختياري)",
      "Enter City": "أدخل المدينة",
      "Touch ID Security": "أمان معرف اللمس",
      "Secure your account with your fingerprint using Touch ID":
          "تأمين حسابك ببصمة إصبعك باستخدام Touch ID",

      "Please place your finger on the fingerprint sensor to get started":
          "يرجى وضع إصبعك على مستشعر بصمة الإصبع للبدء",
      "Enter your email": "أدخل بريدك الإلكتروني",
      "Completed": "مكتمل",
      "Active": "نشط",
      "New": "جديد",
      "Survey Report": "تقرير الاستطلاع",
      "+10 Proposals": "+10 مقترحات",
      "View All Proposal": "عرض جميع العروض",
      "Requests Near You": "الطلبات القريبة منك",
      "Construction Estimation": "تقدير البناء",
      "Apply Now": "قدم الآن",
      "Click to upload": "انقر للتحميل",
      "Tax": "ضريبة",
      "Enter Tax": "أدخل الضريبة",
      "Price": "سعر",
      "Enter Price": "ادخل السعر",
      "Fees": "مصاريف",
      "Request Pricing": "طلب التسعير",
      "Consolation": "استشارة",
      "Total": "تفاصيل",
      "Write Details": "اكتب التفاصيل",
      "Delivering Service": "تقديم الخدمة",

      "Apply": "تقديم",
      "Applied Proposal": "الاقتراح المطبق",
      "Your proposal has been applied. wait approvment from customer,":
          "لقد تم تطبيق اقتراحك. انتظر الموافقة من العميل،",
      "There are a lot of requests waiting for you": "اختر خدمتك وابدأ الان ",
      "Proposals": "اقتراح",
      "Request a service": "اطلب خدمة",
      "Type of activity": "نوع النشاط",
      "Request Service": "اطلب خدمة",
      "Engineering Job": "وظائف هندسية",
      "Purpose Of Pricing": "غرض التسعير",
      "Choose purpose of pricing": "حدد الغرض من التسعير",
      "Choose purpose of cadastral report": "حدد الغرض من التقرير المساحي",
      "Purpose Of Survey Report": "الغرض من التقرير المساحي",
      "Survey Report1": "تقرير المسح 1",
      "Survey Report2": "تقرير المسح 2",
      "Instrument Number": "رقم الصك",
      "Enter Instrument Number": "ادخل رقم الصك",
      "Survey Report Number": "رقم التقرير المساحي",
      "Enter Report Number": "ادخل رقم التقرير المساحي",
      "Type Of Certificate": "نوع الشهادة",
      "Residential": "سكني",
      "Commercial": "تجاري",
      "Investment": "استثماري",
      "Governmental": "حكومي",
      "Industrial": "صناعي",
      "Agree to the ": "توافق على ",
      "Other": "أخري",
      "Enter neighborhood": "أدخل الحي",
      "Piece Number": "رقم القطعة",
      "Enter Piece Number": "أدخل رقم القطعة",
      "Chart Number": "رقم القطعة",
      "Enter chart number": "أدخل رقم القطعة",
      "Applicant Type": "نوع مقدم الطلب",
      "Owner": "مالك",
      "Dealer": "وكيل",
      "Applicant's name": "اسم مقدم الخدمة",
      "Enter Applicant's name": "أدخل اسم المتقدم",
      "ID Number": "رقم الهوية",
      "Enter id number": "أدخل رقم الهوية",
      "Submit Request": "نشر الطلب",
      "What is your purpose for pricing?": "ما هو هدفك من التسعير؟",
      "Survey report": "تقرير مساحي",
      "Building conformity certificate": "شهادة مطابقة البناء",
      "Construction completion certificate": "شهادة إتمام البناء",
      "Construction license": "رخصة البناء",
      "Correcting the condition of an existing building":
          "تصحيح حالة مبنى قائم",
      "Building compliance certificate": "شهادة توافق البناء",
      "Occupancy certificate": "شهادة إشغال",
      "Choose": "اختر",
      "What is your purpose for issuing a survey report?":
          "ما هو الهدف من إصدار تقرير المسح؟",
      "Issuing a building permit": "إصدار رخصة بناء",
      "Expropriation": "نزع ملكية",
      "Emptying": "إفراغ",
      "Digging well": "حفر بئر",
      "Request to sort real estate units": "طلب فرز وحدات عقارية",
      "Sorting built-up lands (duplexes)": "فرز الأراضي المبنية (دوبلكس)",
      "Post Request": "طلب النشر",
      "Your request has been posted. Click to show providers proposals":
          "لقد تم نشر طلبك. انقر لإظهار مقترحات مقدمي الخدمة",
      "Consolation Title": "عنوان الاستشارة",
      "Enter consolation title": "أدخل عنوان الاستشارة",
      "Consolation Type": "نوع الاستشارة",
      "Engineering": "هندسة",
      "Real estate": "عقار",
      "Commitment to pay Meter application dues":
          "الإلتزام بالدفع مستحقات تطبيق متر",
      "Agency Number": "رقم الوكالة",
      "University Degree": "شهادة جامعية",
      "Diploma": "شهادة دبلوم",
      "Specialization": "تخصص",
      "Do you have experience": "هل لديك خبرة؟",
      "Yes": "نعم",
      "No": "لا",
      "Please fill all fields": "لو سمحت أملأ كل الحقول",
      "Please enter valid phone number": "الرجاء إدخال رقم هاتف صحيح",
      "Please enter valid manager phone number":
          "الرجاء إدخال رقم هاتف مدير صالح",
      "Please pick an image": "يرجى اختيار صورة",
      "Please pick image first": "يرجى اختيار صورة أولاً",
      "Both password must be equal": "يجب أن تكون كلمتا المرور متساويتين",
      "You should agree all agreements": "يجب أن توافق على جميع الاتفاقيات",
      "Choose Your Specialization": "اختر تخصصك",
      "If yes, write experience here": "إذا كانت الإجابة نعم، اكتب الخبرة هنا",
      "Enter name": "أدخل الاسم",
      "Enter email": "أدخل البريد الإلكتروني",
      "Preferred city work in": "المدينة المفضلة للعمل فيها",
      "Enter city Name": "أدخل اسم المدينة",
      "Surveying engineer": "مهندس مساحي",
      "Structural engineer": "مهندس إنشائي",
      "Safety engineer": "مهندس سلامة",
      "What is your Specialization?": "ما هو تخصصك؟",
      "Your job has been posted. Click to show providers proposals":
          "لقد تم نشر وظيفتك. انقر لإظهار مقترحات مقدمي الخدمة",
      "Post Job": "وظيفة بعد",
      "Survey Reports": "تقارير المساحة",
      "Building Completion Certificate": "شهادة إنجاز البناء",
      "Design Work": "أأعمال التصميم",
      "Occupancy Certificate": "شهادة الإشغال",
      "Type your review": "اكتب رأيك...",
      "Submit": "يُقدِّم",
      "Service Rating": "تصنيف الخدمة",
      "Accept": "قبول",
      "Decline": "رفض",
      "Electrical Machete": "المنجل الكهربائي",
      "Topcon Auto level AT-B2": "مستوى Topcon التلقائي AT-B2",
      "SAR": "ريال",
      "Welcome To ": "مرحبا بك في ",
      "Your Trusted Partner in Engineering and Surveying Solutions":
          "شريكك الموثوق به في الحلول الهندسية والمساحة",
      "Log In With Phone Number": "تسجيل الدخول برقم الهاتف",
      "Face ID Security": "أمان معرف الوجه",
      "Log In your account with your face using face id":
          "قم بتسجيل الدخول إلى حسابك باستخدام وجهك باستخدام معرف الوجه",
      "Please position your face in front of the camera to authenticate with face id":
          "يرجى وضع وجهك أمام الكاميرا للمصادقة باستخدام معرف الوجه",
      "Write Description": "اكتب الوصف",
      "Click to upload \n your papers": "انقر لتحميل \n أوراقك",
      "Capture": "يأسر",
      "Consolation title": "عنوان العزاء",
      "Consolation type": "نوع العزاء",
      "Write consolation details": "اكتب تفاصيل العزاء",
      "Click to upload\nWork copy here": "انقر لتحميل\nنسخة العمل هنا",
      "Electronic signature": "التوقيع الإلكتروني",
      "Enter office name": "أدخل اسم المكتب",
      "Print": "مطبعة",
      "Send Work": "أرسل العمل",
      "work has been sent": "تم إرسال العمل",
      "Congratulations! Your work has been sent": "تهانينا! لقد تم إرسال عملك",
      "Consolation Delivery": "تسليم العزاء",

      "ID number": "رقم الهوية",
      "Enter Id number": "أدخل رقم الهوية",
      "Instrumental Number": "رقم آلي",
      "Enter Instrumental Number": "أدخل رقم الآلة",
      "Chart number": "رقم الرسم البياني",
      "Enter Chart number": "أدخل رقم المخطط",
      /////Push//////////
      "Street Name": "اسم الشارع",
      "Enter street name": "أدخل اسم الشارع",
      "Enter the property properties": "أدخل خصائص العقار",
      "Click to Upload\n Work from Autocad": "انقر لتحميل\n العمل من أوتوكاد",
      ////////////////////////////Abdullah Start from here///////////////////
      "Electronic Signature": "التوقيع الإلكتروني",
      "North Direction": "اتجاه الشمال",
      "Enter height": "أدخل الارتفاع",
      "Height": "الارتفاع",
      "Enter boundaries": "أدخل الحدود",
      "Boundaries by nature": "الحدود بطبيعتها",
      "Boundaries by deed": "الحدود بفعل",
      "Boundaries by plan": "الحدود حسب الخطة",
      "Next Direction": "الاتجاه التالي",
      "East Direction": "إتجاه الشرق",
      "South Direction": "اتجاه الجنوب",
      "West Direction": "اتجاه الغرب",
      "Title": "عنوان",
      "Enter title": "أدخل العنوان",
      "Choose Service Type": "اختر نوع الخدمة",
      "Service Type": "نوع الخدمة",
      "Agency number": "رقم الوكالة",
      "Enter Description": "أدخل الوصف",
      "Meter Store": "متجر متر",
      "Error": "خطأ",
      ///////////////Short Text/////////////////////
      "is required": "مطلوب",
      "Email is required": "البريد الإلكتروني مطلوب",
      "Email must be valid": "يجب ان يكون البريد الاكتروني صحيح",
      "Length must be greater than": "الطول يجب أن يكون أكبر من",
      "Length must be less than": "يجب أن يكون الطول أقل من",
      "- Minimum angle reading 0.1 second - 4000m prism range with accuracy 1.5 mm + 2ppm - 500m NP range with accuracy 2 mm+ 2ppm - Fast and ultra-powerful advance EDM - Advanced Angle Accuracy , IACS - Measuring time: Fine 0.9 sec, Rapid 0.6 sec, tracking 0.4 sec - Touch screen, Large Graphics display":
          "- أدنى قراءة للزاوية 0.1 ثانية - مدى المنشور 4000 متر بدقة 1.5 ملم + 2 جزء في المليون - مدى NP 500 متر بدقة 2 ملم + 2 جزء في المليون - EDM متقدم سريع وقوي للغاية - دقة زاوية متقدمة، IACS - وقت القياس: دقيق 0.9 ثانية، سريع 0.6 ثانية، تتبع 0.4 ثانية - شاشة لمس، عرض رسومات كبير",

      //////////////////////////////////////Large Text
      "Lorem ipsum dolor sit amet consectetur. Dictumst aenean sit viverra sapien purus phasellus. Pulvinar viverra tincidunt aenean velit ut nisl diam. Eu sed commodo pellentesque augue tincidunt. Urna euis....":
          "لوريم إيبسوم دولار سيت أميت كونسيكتيتور. ديكتومست أنيان سيت فيفيرا سابين بوروس فاسيلوس. بولفينار فيفيرا تينسيند أنيان فيليت أوت نيسل ديام. إيو سيد كومودو بينتيسكيلاي أوجيو تينسيند. أورنا إويس....",
      "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles. Ma quande lingues coalesce, li grammatica del resultant lingue es plu simplic e regulari quam ti del coalescent lingues. Li nov lingua franca va esser plu simplic e regulari quam li existent Europan lingues.\n\nIt va esser tam simplic quam Occidental in fact, it va esser Occidental. A un Angleso it va semblar un simplificat Angles, quam un skeptic Cambridge amico dit me que Occidental es.Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.":
          "اللغات الأوروبية هي أعضاء في نفس العائلة. الوجود المنفصل لها هو خرافة. من أجل العلم، الموسيقى، الرياضة، إلخ، تستخدم أوروبا نفس المفردات. تختلف اللغات فقط في القواعد، النطق والمفردات الأكثر شيوعًا. كل شيء يشير إلى ضرورة لغة مشتركة جديدة: يرفض الناس الاستمرار في دفع تكاليف الترجمة الباهظة. ولكن سيكون من الضروري فقط توحيد القواعد والنطق والكلمات الأكثر شيوعًا. عندما تندمج اللغات، تصبح قواعد اللغة الناتجة أبسط وأكثر انتظامًا من تلك الخاصة باللغات المندمجة. ستكون اللغة المشتركة الجديدة أبسط وأكثر انتظامًا من اللغات الأوروبية الحالية.\n\nستكون بسيطة مثل الأوكسيدنتال في الواقع، ستكون الأوكسيدنتال. بالنسبة لإنجليزي، سيبدو الأمر وكأنه إنجليزية مبسطة، كما قال لي صديق متشكك من كامبريدج أن الأوكسيدنتال كذلك. اللغات الأوروبية هي أعضاء في نفس العائلة. الوجود المنفصل لها هو خرافة. من أجل العلم، الموسيقى، الرياضة، إلخ، تستخدم أوروبا نفس المفردات. تختلف اللغات فقط في القواعد، النطق والمفردات الأكثر شيوعًا. كل شيء يشير إلى ضرورة لغة مشتركة جديدة: يرفض الناس الاستمرار في دفع تكاليف الترجمة الباهظة. ولكن سيكون من الضروري فقط توحيد القواعد والنطق والكلمات الأكثر شيوعًا.",
      """
  To create a new account, please follow these simple steps: 

Open the app and navigate to the login screen. 
Below the login form, you'll see an option to "Register" Tap on that. 
You will be prompted to enter your Phone Number, Email and Full Name for your account. Please make sure to use a valid Phone Number. 
After entering your Phone Number, Email and Full Name, tap on the "Register" button.
A code will be sent to your phone number provided for verification. Please check your inbox and enter the code in the Verification screen to verify your account. 
Once your account is verified, the app will automatically log you in. 
You can enter some other personal information or skip it. 
You can set the required security level for your account or ignore it. 
You are now done creating your account. 

If you encounter any issues during the sign-up process, feel free to reach out to our support team for assistance.
  """: "لإنشاء حساب جديد، يرجى اتباع هذه الخطوات البسيطة:\n\nافتح التطبيق وانتقل إلى شاشة تسجيل الدخول.\nأسفل نموذج تسجيل الدخول، سترى خيار \"التسجيل\" انقر عليه.\nسيتم طلب إدخال رقم هاتفك، البريد الإلكتروني والاسم الكامل لحسابك. يرجى التأكد من استخدام رقم هاتف صالح.\nبعد إدخال رقم هاتفك، البريد الإلكتروني والاسم الكامل، انقر على زر \"التسجيل\".\nسيتم إرسال رمز إلى رقم هاتفك المُقدم للتحقق. يرجى التحقق من صندوق الوارد وإدخال الرمز في شاشة التحقق لتأكيد حسابك.\nبمجرد تأكيد حسابك، سيقوم التطبيق بتسجيل دخولك تلقائياً.\nيمكنك إدخال بعض المعلومات الشخصية الأخرى أو تخطيها.\nيمكنك ضبط مستوى الأمان المطلوب لحسابك أو تجاهله.\nلقد انتهيت الآن من إنشاء حسابك.\n\nإذا واجهت أي مشكلة أثناء عملية التسجيل، لا تتردد في الاتصال بفريق الدعم لدينا للحصول على المساعدة."
    };
  }
}
